### ISSUE TITLE
文章内代码地址失效

### ISSUE THREAD

**Issue by HyperClockUp** [Daotin/Web#3]
https://github.com/Daotin/web/blob/master/11-%E7%A7%BB%E5%8A%A8Web/02-JD%E7%A7%BB%E5%8A%A8%E7%AB%AF%E7%BD%91%E9%A1%B5%EF%BC%8C%E7%A7%BB%E5%8A%A8%E8%A7%A6%E5%B1%8F%E4%BA%8B%E4%BB%B6.md

中的

https://github.com/Daotin/Web/tree/master/Code/src/11/jd.zip

404 ，master分支内没有Code目录

**Comment by Daotin** [comment]
Hi，仿京东首页源码如下：

[0-jd.zip](https://github.com/Daotin/web/files/4001590/0-jd.zip)

**Comment by Daotin** [comment]
> https://github.com/Daotin/web/blob/master/11-%E7%A7%BB%E5%8A%A8Web/02-JD%E7%A7%BB%E5%8A%A8%E7%AB%AF%E7%BD%91%E9%A1%B5%EF%BC%8C%E7%A7%BB%E5%8A%A8%E8%A7%A6%E5%B1%8F%E4%BA%8B%E4%BB%B6.md
> 
> 中的
> 
> https://github.com/Daotin/Web/tree/master/Code/src/11/jd.zip
> 
> 404 ，master分支内没有Code目录

Hi，仿京东首页源码如下：

[0-jd.zip](https://github.com/Daotin/web/files/4001590/0-jd.zip)
